<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {{ title ? title : "Home" }} </title>
    <link rel="stylesheet" href="/css/main.css">
</head>
<body class="subpage">
    
<header id="header">
    <div class="inner">
        <a href="index.html" class="logo"><strong>Systema de Saldo</strong></a>
        <nav id="nav">
            <a href="index.html">Login</a>
            <a href="generic.html">Cadastrar-se</a>
        </nav>
        <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
    </div>
</header>

{% block main %}{% endblock %}

</body>
</html>